using DSkin.Forms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Plugin.Express
{
    public class Express
    {

        private static string url = "http://api.aikuaidi.cn/rest";
        private static string key = "3168b7ddacfc495f9d1bd0f4d20178d6";
        private static string ord = "desc";
        private static string show = "json";

        public static Result getExpress(string typee,string order)
        {
            Dictionary<string, string> dic = new Dictionary<string, string>();
            dic.Add("key",key);
            dic.Add("id", typee);
            dic.Add("order", order);
            dic.Add("ord", ord);
            dic.Add("show", show);
            string str = Common.HttpHelper.Post(url,dic);
            Result result = Common.JsonHelper.JSONString<Result>(str);
            if (result.errCode == 0) return result;
            switch (result.errCode)
            {
                case 1:
                    DSkinMessageBox.Show("快递KEY无效");
                    return null;
                case 2:
                    DSkinMessageBox.Show("快递代号无效");
                    return null;
                case 3:
                    DSkinMessageBox.Show("访问次数达到最大额度");
                    return null;
                case 4:
                    DSkinMessageBox.Show("查询服务器返回错误即返回状态码非200");
                    return null;
                case 5:
                    DSkinMessageBox.Show("查询执行出错");
                    return null;
                default:
                    DSkinMessageBox.Show("接口错误");
                    return null;
            }
        }
        public static string getExpress2(string typer, string order)
        {
            Dictionary<string, string> dic = new Dictionary<string, string>();
            dic.Add("key", key);
            dic.Add("id", typer);
            dic.Add("order", order);
            dic.Add("ord", ord);
            dic.Add("show", show);
            string result = Common.HttpHelper.Post(url, dic);
            return result;
        }

        public static List<ExpressCode> getExperssCode(bool is_quick=false)
        {
            List<ExpressCode> code = new List<ExpressCode>();
            code.Add(new ExpressCode() { code = "china_ems", name = "中国 EMS(China EMS)" });
            code.Add(new ExpressCode() { code = "yuantong", name = "圆通快递" });
            code.Add(new ExpressCode() { code = "shentong", name = "申通快递" });
            code.Add(new ExpressCode() { code = "zhongtong", name = "中通快递" });
            code.Add(new ExpressCode() { code = "debang", name = "德邦物流" });
            code.Add(new ExpressCode() { code = "huitong", name = "汇通快递" });
            code.Add(new ExpressCode() { code = "tiantian", name = "天天快递" });
            code.Add(new ExpressCode() { code = "yunda", name = "韵达快递" });
            code.Add(new ExpressCode() { code = "ankd", name = "安能快递" });
            code.Add(new ExpressCode() { code = "zjs", name = "宅急送快递" });
            code.Add(new ExpressCode() { code = "yousu", name = "优速快递" });
            code.Add(new ExpressCode() { code = "jingdong", name = "京东快递" });
            if (is_quick) return code;
            code.Add(new ExpressCode() { code = "ydky", name = "韵达快运" });
            code.Add(new ExpressCode() { code = "htky", name = "百世快运" });
            code.Add(new ExpressCode() { code = "shunfeng", name = "顺丰快递" });
            code.Add(new ExpressCode() { code = "bestex", name = "百世快递" });
            code.Add(new ExpressCode() { code= "suning", name= "苏宁快递" });
            code.Add(new ExpressCode() { code = "4px", name = "递四方(4PX)" });
            code.Add(new ExpressCode() { code = "j_net", name = "J-NET捷网" });
            code.Add(new ExpressCode() { code = "xunsu", name = "迅速快递" });
            code.Add(new ExpressCode() { code = "aol", name = "AOL快递" });
            code.Add(new ExpressCode() { code = "china_post", name = "中国邮政(China Post)" });
            code.Add(new ExpressCode() { code = "correo_argentino", name = "阿根廷邮政(Argentino Post)" });
            code.Add(new ExpressCode() { code = "apc", name = "APC Postal Logistics" });
            code.Add(new ExpressCode() { code = "arrowxl", name = "Arrow XL" });
            code.Add(new ExpressCode() { code = "aruba_post", name = "阿鲁巴邮政(Aruba Post)" });
            code.Add(new ExpressCode() { code = "asendia_de", name = "Asendia Germany" });
            code.Add(new ExpressCode() { code = "asendia_hk", name = "Asendia HK" });
            code.Add(new ExpressCode() { code = "anjun", name = "安骏物流(Anjun Logistics)" });
            code.Add(new ExpressCode() { code = "airspeed", name = "Airspeed International Corporation" });
            code.Add(new ExpressCode() { code = "airwings_india", name = "Airwings Courier Express India" });
            code.Add(new ExpressCode() { code = "al8856", name = "阿里电商物流(Ali Business Logistics)" });
            code.Add(new ExpressCode() { code = "allekurier", name = "AlleKurier" });
            code.Add(new ExpressCode() { code = "alljoy", name = "Alljoy" });
            code.Add(new ExpressCode() { code = "alpha_fast", name = "Alpha Fast快递" });
            code.Add(new ExpressCode() { code = "andorra_post", name = "安道尔邮政(Andorra Post)" });
            code.Add(new ExpressCode() { code = "aus", name = "澳世速递(Ausworld Express)" });
            code.Add(new ExpressCode() { code = "australia-ems", name = "澳大利亚 EMS(Australia EMS)" });
            code.Add(new ExpressCode() { code = "asmred", name = "ASM" });
            code.Add(new ExpressCode() { code = "australia_post", name = "澳大利亚邮政(Australia Post)" });
            code.Add(new ExpressCode() { code = "austria_post", name = "奥地利邮政(Austrian Post)" });
            code.Add(new ExpressCode() { code = "azerbaijan_post", name = "阿塞拜疆邮政(Azerbaijan Post)" });
            code.Add(new ExpressCode() { code = "aramex", name = "Aramex" });
            code.Add(new ExpressCode() { code = "abf", name = "ABF Freight" });
            code.Add(new ExpressCode() { code = "aland_post", name = "奥兰群岛芬兰邮政(aland Post)" });
            code.Add(new ExpressCode() { code = "afghan_post", name = "阿富汗邮政(Afghan Post)" });
            code.Add(new ExpressCode() { code = "an_post", name = "爱尔兰邮政(An Post)" });
            code.Add(new ExpressCode() { code = "auexpress", name = "澳邮中国快运(Auexpress)" });
            code.Add(new ExpressCode() { code = "abxexpress_my", name = "ABX Express" });
            code.Add(new ExpressCode() { code = "acommerce", name = "ACommerce" });
            code.Add(new ExpressCode() { code = "acscourier", name = "ACS Courier" });
            code.Add(new ExpressCode() { code = "adicional", name = "Adicional Logistics" });
            code.Add(new ExpressCode() { code = "adsone", name = "ADSOne快递" });
            code.Add(new ExpressCode() { code = "air21", name = "AIR21" });
            code.Add(new ExpressCode() { code = "airpak_express", name = "Airpak Express" });
            code.Add(new ExpressCode() { code = "aae", name = "AAE快递" });
            code.Add(new ExpressCode() { code = "axd", name = "安信达快递" });
            code.Add(new ExpressCode() { code = "aj", name = "安捷快递" });
            code.Add(new ExpressCode() { code = "bfdf", name = "百福东方" });
            code.Add(new ExpressCode() { code = "bgpyghx", name = "包裹、平邮、挂号信" });
            code.Add(new ExpressCode() { code = "8europe", name = "败欧洲(8europe)" });
            code.Add(new ExpressCode() { code = "brazil_correios", name = "巴西邮政(Brazil Correios)" });
            code.Add(new ExpressCode() { code = "360zebra", name = "斑马物联网(360zebra)" });
            code.Add(new ExpressCode() { code = "belpochta", name = "白俄罗斯邮政(Belarus Post)" });
            code.Add(new ExpressCode() { code = "barbados_post", name = "巴巴多斯邮政(Barbados Post)" });
            code.Add(new ExpressCode() { code = "belgium_post", name = "比利时邮政(Bpost)" });
            code.Add(new ExpressCode() { code = "bgn", name = "布谷鸟快递" });
            code.Add(new ExpressCode() { code = "benin_post", name = "贝宁邮政(Benin Post)" });
            code.Add(new ExpressCode() { code = "bluedart", name = "Bluedart" });
            code.Add(new ExpressCode() { code = "bombino_express", name = "Bombino Express" });
            code.Add(new ExpressCode() { code = "bermuda_post", name = "百慕大邮政(Bermuda Post)" });
            code.Add(new ExpressCode() { code = "bhutan_post", name = "不丹邮政(Bhutan Post)" });
            code.Add(new ExpressCode() { code = "bosnia_and_herzegovina_post", name = "波黑邮政(Bosnia And Herzegovina Post)" });
            code.Add(new ExpressCode() { code = "bondscouriers", name = "Bonds Couriers" });
            code.Add(new ExpressCode() { code = "pakistan_post", name = "巴基斯坦邮政(Pakistan Post)" });
            code.Add(new ExpressCode() { code = "bsi", name = "佰事达(BSI express)" });
            code.Add(new ExpressCode() { code = "bahrain-post", name = "巴林邮政(Bahrain Post)" });
            code.Add(new ExpressCode() { code = "bartolini", name = "BRT Bartolini" });
            code.Add(new ExpressCode() { code = "bab-ru", name = "北北国际(BAB international)" });
            code.Add(new ExpressCode() { code = "cbtsd", name = "北泰物流(Better)" });
            code.Add(new ExpressCode() { code = "bulgaria_post", name = "保加利亚邮政(Bulgaria Post)" });
            code.Add(new ExpressCode() { code = "beihaiguoji", name = "贝海国际速递" });
            code.Add(new ExpressCode() { code = "botswana_post", name = "博茨瓦纳邮政(Botswana Post)" });
            code.Add(new ExpressCode() { code = "burundi_post", name = "布隆迪邮政(Burundi Post)" });
            code.Add(new ExpressCode() { code = "bmwl", name = "斑马物联网" });
            code.Add(new ExpressCode() { code = "btgj", name = "邦通国际" });
            code.Add(new ExpressCode() { code = "correos_panama", name = "巴拿马邮政" });
            code.Add(new ExpressCode() { code = "cc", name = "C&C速递" });
            code.Add(new ExpressCode() { code = "chunfeng", name = "春风物流" });
            code.Add(new ExpressCode() { code = "canpar", name = "Canpar Courier" });
            code.Add(new ExpressCode() { code = "cbl_logistica", name = "CBL Logistics" });
            code.Add(new ExpressCode() { code = "chukou1", name = "出口易物流" });
            code.Add(new ExpressCode() { code = "cnilink", name = "CNI中印物流" });
            code.Add(new ExpressCode() { code = "cnexps", name = "CNE国际快递(CNE Express)" });
            code.Add(new ExpressCode() { code = "cacesapostal", name = "Cacesa南美专线(Cacesa Postal)" });
            code.Add(new ExpressCode() { code = "cdek", name = "CDEK快递" });
            code.Add(new ExpressCode() { code = "chengji", name = "城际快递" });
            code.Add(new ExpressCode() { code = "chaofeng", name = "超峰快递" });
            code.Add(new ExpressCode() { code = "cxwl", name = "传喜物流" });
            code.Add(new ExpressCode() { code = "chengguang", name = "程光快递" });
            code.Add(new ExpressCode() { code = "coe", name = "东方快递" });
            code.Add(new ExpressCode() { code = "ctwl", name = "长通物流" });
            code.Add(new ExpressCode() { code = "cszx", name = "城市之星物流" });
            code.Add(new ExpressCode() { code = "cs", name = "城市100快递" });
            code.Add(new ExpressCode() { code = "chuanzhi", name = "传志快递" });
            code.Add(new ExpressCode() { code = "dhl", name = "DHL快递" });
            code.Add(new ExpressCode() { code = "dpex", name = "DPEX快递" });
            code.Add(new ExpressCode() { code = "dsf", name = "递四方速递" });
            code.Add(new ExpressCode() { code = "dtwl", name = "大田物流" });
            code.Add(new ExpressCode() { code = "dywl", name = "大洋物流" });
            code.Add(new ExpressCode() { code = "ds", name = "D速快递" });
            code.Add(new ExpressCode() { code = "ddwl", name = "大达物流" });
            code.Add(new ExpressCode() { code = "dwz", name = "递五洲国际物流" });
            code.Add(new ExpressCode() { code = "deutsche_post", name = "德国邮政(Deutsche Post)" });
            code.Add(new ExpressCode() { code = "dhl_germany", name = "德国DHL" });
            code.Add(new ExpressCode() { code = "dpe_express", name = "递必易" });
            code.Add(new ExpressCode() { code = "djkj", name = "东骏快捷物流" });
            code.Add(new ExpressCode() { code = "dn", name = "丹鸟快递" });
            code.Add(new ExpressCode() { code = "dadaowuliu", name = "大道物流" });
            code.Add(new ExpressCode() { code = "ewe", name = "ewe快递" });
            code.Add(new ExpressCode() { code = "139express", name = "139快递(139 ECONOMIC Package)" });
            code.Add(new ExpressCode() { code = "ems", name = "EMS快递" });
            code.Add(new ExpressCode() { code = "fedex", name = "FEDEX国际快递" });
            code.Add(new ExpressCode() { code = "fedexcn", name = "FEDEX国内快递" });
            code.Add(new ExpressCode() { code = "fkd", name = "飞康达快递" });
            code.Add(new ExpressCode() { code = "fbwl", name = "飞邦物流" });
            code.Add(new ExpressCode() { code = "feibao", name = "飞豹快递" });
            code.Add(new ExpressCode() { code = "feihu", name = "飞狐快递" });
            code.Add(new ExpressCode() { code = "colissimo", name = "法国邮政-(Colissimo)" });
            code.Add(new ExpressCode() { code = "feiyang", name = "飞洋快递" });
            code.Add(new ExpressCode() { code = "fanyu", name = "凡宇快递" });
            code.Add(new ExpressCode() { code = "fangfangda", name = "方方达物流" });
            code.Add(new ExpressCode() { code = "feiying", name = "飞鹰物流" });
            code.Add(new ExpressCode() { code = "fengda", name = "丰达快递" });
            code.Add(new ExpressCode() { code = "flytexpress", name = "飞特物流(Flyt Express)" });
            code.Add(new ExpressCode() { code = "fd_express", name = "方递物流" });
            code.Add(new ExpressCode() { code = "far800", name = "泛远国际物流" });
            code.Add(new ExpressCode() { code = "chronopost", name = "法国 EMS(France EMS - Chronopost)" });
            code.Add(new ExpressCode() { code = "arkexpress", name = "方舟国际速递(Ark express)" });
            code.Add(new ExpressCode() { code = "ftd", name = "富腾达快递" });
            code.Add(new ExpressCode() { code = "quantium", name = "冠庭国际物流" });
            code.Add(new ExpressCode() { code = "gjyzbg", name = "国际邮政包裹" });
            code.Add(new ExpressCode() { code = "colombia_post", name = "哥伦比亚邮政(Colombia Post)" });
            code.Add(new ExpressCode() { code = "gjbg", name = "国际包裹" });
            code.Add(new ExpressCode() { code = "guangtong", name = "广通速递" });
            code.Add(new ExpressCode() { code = "gtsd", name = "高铁速递" });
            code.Add(new ExpressCode() { code = "guada", name = "冠达快递" });
            code.Add(new ExpressCode() { code = "gdems", name = "广东ems快递" });
            code.Add(new ExpressCode() { code = "2go", name = "2GO" });
            code.Add(new ExpressCode() { code = "gsdwl", name = "共速达物流" });
            code.Add(new ExpressCode() { code = "guotong", name = "国通快递" });
            code.Add(new ExpressCode() { code = "gznd", name = "港中能达" });
            code.Add(new ExpressCode() { code = "henglu", name = "恒路物流" });
            code.Add(new ExpressCode() { code = "huiqiang", name = "汇强快递" });
            code.Add(new ExpressCode() { code = "hxlwl", name = "华夏龙物流" });
            code.Add(new ExpressCode() { code = "hswl", name = "昊盛物流" });
            code.Add(new ExpressCode() { code = "haihong", name = "山东海红快递" });
            code.Add(new ExpressCode() { code = "t_cat", name = "黑貓宅急便(T Cat)" });
            code.Add(new ExpressCode() { code = "1hcang", name = "1号仓" });
            code.Add(new ExpressCode() { code = "aplus100", name = "美国汉邦快递(A PLUS EXPRESS)" });
            code.Add(new ExpressCode() { code = "huaqi", name = "华企快递" });
            code.Add(new ExpressCode() { code = "huangmajia", name = "黄马甲快递" });
            code.Add(new ExpressCode() { code = "hongtai", name = "鸿泰物流" });
            code.Add(new ExpressCode() { code = "hezhong", name = "合众速递" });
            code.Add(new ExpressCode() { code = "hsd", name = "华世达快递" });
            code.Add(new ExpressCode() { code = "hhexp", name = "华翰物流" });
            code.Add(new ExpressCode() { code = "huilogistics", name = "荟千物流" });
            code.Add(new ExpressCode() { code = "korea_post", name = "韩国邮政(Korea Post)" });
            code.Add(new ExpressCode() { code = "antilles_post", name = "荷属安的列斯荷兰邮政(Antilles Post)" });
            code.Add(new ExpressCode() { code = "canada_post", name = "加拿大邮政(Canada Post)" });
            code.Add(new ExpressCode() { code = "buylogic", name = "捷买送(Buylogic)" });
            code.Add(new ExpressCode() { code = "jt", name = "极兔快递" });
            code.Add(new ExpressCode() { code = "jdwl", name = "金大物流" });
            code.Add(new ExpressCode() { code = "jgwl", name = "景光物流" });
            code.Add(new ExpressCode() { code = "czech_post", name = "捷克邮政" });
            code.Add(new ExpressCode() { code = "cambodia_post", name = "柬埔寨邮政(Cambodia Post)" });
            code.Add(new ExpressCode() { code = "jiete", name = "捷特快递" });
            code.Add(new ExpressCode() { code = "jincheng", name = "锦程快递" });
            code.Add(new ExpressCode() { code = "jldt", name = "嘉里大通物流" });
            code.Add(new ExpressCode() { code = "jywl", name = "佳怡物流" });
            code.Add(new ExpressCode() { code = "jiaji", name = "佳吉快运" });
            code.Add(new ExpressCode() { code = "jiayunmei", name = "加运美快递" });
            code.Add(new ExpressCode() { code = "jingguang", name = "京广快递" });
            code.Add(new ExpressCode() { code = "jinyue", name = "晋越快递" });
            code.Add(new ExpressCode() { code = "kuaijie", name = "快捷快递" });
            code.Add(new ExpressCode() { code = "klwl", name = "康力物流" });
            code.Add(new ExpressCode() { code = "kjwl", name = "科捷物流" });
            code.Add(new ExpressCode() { code = "kysy", name = "跨越速运" });
            code.Add(new ExpressCode() { code = "krwl", name = "宽容物流" });
            code.Add(new ExpressCode() { code = "campost", name = "喀麦隆邮政(Cameroon Post)" });
            code.Add(new ExpressCode() { code = "lvzhou", name = "绿洲快递" });
            code.Add(new ExpressCode() { code = "belize_post", name = "伯利兹邮政(Belize Post)" });
            code.Add(new ExpressCode() { code = "bt_exp", name = "利佳顺(LJS)" });
            code.Add(new ExpressCode() { code = "lanhu", name = "蓝狐快递" });
            code.Add(new ExpressCode() { code = "litong", name = "立通快递" });
            code.Add(new ExpressCode() { code = "blueskyexpress", name = "蓝天快递(Blue Sky)" });
            code.Add(new ExpressCode() { code = "longbang", name = "龙邦快递" });
            code.Add(new ExpressCode() { code = "lianhaotong", name = "联昊通快递" });
            code.Add(new ExpressCode() { code = "lejiedi", name = "乐捷递快递" });
            code.Add(new ExpressCode() { code = "lijisong", name = "立即送" });
            code.Add(new ExpressCode() { code = "minbang", name = "民邦快递" });
            code.Add(new ExpressCode() { code = "minhang", name = "民航快递" });
            code.Add(new ExpressCode() { code = "meiguo", name = "美国快递" });
            code.Add(new ExpressCode() { code = "usps", name = "美国邮政(USPS)" });
            code.Add(new ExpressCode() { code = "correos_mexico", name = "墨西哥邮政(Mexico Post)" });
            code.Add(new ExpressCode() { code = "meilong", name = "美龙快递" });
            code.Add(new ExpressCode() { code = "miuson-international", name = "深圳淼信国际物流" });
            code.Add(new ExpressCode() { code = "bangladesh_ems", name = "孟加拉国 EMS(Bangladesh EMS)" });
            code.Add(new ExpressCode() { code = "huidaex", name = "美国汇达快递" });
            code.Add(new ExpressCode() { code = "jdpplus", name = "美国急递速递" });
            code.Add(new ExpressCode() { code = "nbky", name = "南北快运" });
            code.Add(new ExpressCode() { code = "newl", name = "尼尔物流" });
            code.Add(new ExpressCode() { code = "ocs", name = "OCS快递" });
            code.Add(new ExpressCode() { code = "pinganda", name = "平安达快递" });
            code.Add(new ExpressCode() { code = "17postservice", name = "17 Post Service" });
            code.Add(new ExpressCode() { code = "pinjun", name = "品骏快递" });
            code.Add(new ExpressCode() { code = "efspost", name = "平安快递(EFSPost)" });
            code.Add(new ExpressCode() { code = "qichen", name = "启辰国际物流(venucia)" });
            code.Add(new ExpressCode() { code = "quanfeng", name = "全峰快递" });
            code.Add(new ExpressCode() { code = "quanyi", name = "全一快递" });
            code.Add(new ExpressCode() { code = "quanchen", name = "全晨快递" });
            code.Add(new ExpressCode() { code = "quanritong", name = "全日通快递" });
            code.Add(new ExpressCode() { code = "rufengda", name = "如风达快递" });
            code.Add(new ExpressCode() { code = "rrs", name = "日日顺物流" });
            code.Add(new ExpressCode() { code = "japan_post", name = "日本邮政(Japan Post)" });
            code.Add(new ExpressCode() { code = "rongteng", name = "荣腾快递" });
            code.Add(new ExpressCode() { code = "stky", name = "苏通快运" });
            code.Add(new ExpressCode() { code = "showl", name = "森鸿物流" });
            code.Add(new ExpressCode() { code = "shunda", name = "顺达快递" });
            code.Add(new ExpressCode() { code = "suteng", name = "速腾快递" });
            code.Add(new ExpressCode() { code = "suyd56", name = "速邮达物流" });
            code.Add(new ExpressCode() { code = "shengbangwuliu", name = "晟邦物流" });
            code.Add(new ExpressCode() { code = "saicheng", name = "赛诚国际物流" });
            code.Add(new ExpressCode() { code = "sxexpress", name = "三象速递" });
            code.Add(new ExpressCode() { code = "cainiao", name = "速卖通线上物流" });
            code.Add(new ExpressCode() { code = "sunyou", name = "顺友物流" });
            code.Add(new ExpressCode() { code = "fastgo", name = "速派快递FastGo(Fastgo)" });
            code.Add(new ExpressCode() { code = "shiyun", name = "世运快递" });
            code.Add(new ExpressCode() { code = "stwl", name = "速通物流" });
            code.Add(new ExpressCode() { code = "suer", name = "速尔快递" });
            code.Add(new ExpressCode() { code = "santai", name = "三态速递" });
            code.Add(new ExpressCode() { code = "shenghui", name = "盛辉物流" });
            code.Add(new ExpressCode() { code = "shengfeng", name = "盛丰物流" });
            code.Add(new ExpressCode() { code = "shengan", name = "圣安物流" });
            code.Add(new ExpressCode() { code = "saiaodi", name = "赛澳递" });
            code.Add(new ExpressCode() { code = "tnt", name = "TNT快递" });
            code.Add(new ExpressCode() { code = "thtx", name = "通和天下物流" });
            code.Add(new ExpressCode() { code = "tcwl", name = "通成物流" });
            code.Add(new ExpressCode() { code = "tdhy", name = "天地华宇" });
            code.Add(new ExpressCode() { code = "13_ten", name = "13ten" });
            code.Add(new ExpressCode() { code = "138sd", name = "泰国138快递(138sd)" });
            code.Add(new ExpressCode() { code = "chinz56", name = "秦远物流" });
            code.Add(new ExpressCode() { code = "tengdawuliu", name = "腾达物流" });
            code.Add(new ExpressCode() { code = "takesend", name = "泰嘉物流" });
            code.Add(new ExpressCode() { code = "tianyue", name = "天越物流" });
            code.Add(new ExpressCode() { code = "ups", name = "UPS国际快递" });
            code.Add(new ExpressCode() { code = "weibang", name = "伟邦快递" });
            code.Add(new ExpressCode() { code = "weitepai", name = "微特派快递" });
            code.Add(new ExpressCode() { code = "wxwl", name = "万象物流" });
            code.Add(new ExpressCode() { code = "wanbexpress", name = "万邦速达(Wanb Express)" });
            code.Add(new ExpressCode() { code = "wanbo", name = "万博快递" });
            code.Add(new ExpressCode() { code = "wise_express", name = "万色速递" });
            code.Add(new ExpressCode() { code = "wanli", name = "万里物流" });
            code.Add(new ExpressCode() { code = "oneworldexpress", name = "万欧国际物流" });
            code.Add(new ExpressCode() { code = "brunei_post", name = "文莱邮政(Brunei Post)" });
            code.Add(new ExpressCode() { code = "xqwl", name = "星前物流" });
            code.Add(new ExpressCode() { code = "xdexpress", name = "迅达速递" });
            code.Add(new ExpressCode() { code = "qexpress", name = "新西兰易达通" });
            code.Add(new ExpressCode() { code = "hong_kong_post", name = "香港邮政(Hong Kong Post)" });
            code.Add(new ExpressCode() { code = "xinjie", name = "新杰物流" });
            code.Add(new ExpressCode() { code = "xlyt", name = "祥龙运通" });
            code.Add(new ExpressCode() { code = "correos_spain", name = "西班牙邮政(Correos)" });
            code.Add(new ExpressCode() { code = "xfwl", name = "信丰物流" });
            code.Add(new ExpressCode() { code = "xindan", name = "新蛋物流" });
            code.Add(new ExpressCode() { code = "xinbang", name = "新邦物流" });
            code.Add(new ExpressCode() { code = "yibang", name = "一邦快递" });
            code.Add(new ExpressCode() { code = "yuntong", name = "运通快递" });
            code.Add(new ExpressCode() { code = "yzjc", name = "元智捷诚快递" });
            code.Add(new ExpressCode() { code = "yuanfeihang", name = "原飞航快递" });
            code.Add(new ExpressCode() { code = "yafeng", name = "亚风快递" });
            code.Add(new ExpressCode() { code = "ycwl", name = "远成物流" });
            code.Add(new ExpressCode() { code = "yuefeng", name = "越丰快递" });
            code.Add(new ExpressCode() { code = "ymdd", name = "壹米滴答物流" });
            code.Add(new ExpressCode() { code = "2uex", name = "优优速递(2U Express)" });
            code.Add(new ExpressCode() { code = "8dt", name = "永利八达通(Profit Fields)" });
            code.Add(new ExpressCode() { code = "yitongda", name = "易通达" });
            code.Add(new ExpressCode() { code = "yzxb", name = "邮政小包" });
            code.Add(new ExpressCode() { code = "ghx", name = "挂号信" });
            code.Add(new ExpressCode() { code = "ande", name = "安得物流" });
            code.Add(new ExpressCode() { code = "ycky", name = "远成快运" });
            code.Add(new ExpressCode() { code = "yad", name = "源安达快递" });
            code.Add(new ExpressCode() { code = "yxwl", name = "宇鑫物流" });
            code.Add(new ExpressCode() { code = "espeedpost", name = "易速国际物流(Espeedpost)" });
            code.Add(new ExpressCode() { code = "armenia_post", name = "亚美尼亚邮政(Armenia Post)" });
            code.Add(new ExpressCode() { code = "parcel_force", name = "英国邮政(Parcel Force)" });
            code.Add(new ExpressCode() { code = "yunexpress", name = "云途物流" });
            code.Add(new ExpressCode() { code = "royal_mail", name = "英国皇家邮政(United Kingdom Royal Mail)" });
            code.Add(new ExpressCode() { code = "yzt", name = "一站通速运" });
            code.Add(new ExpressCode() { code = "ubonex", name = "优邦速运" });
            code.Add(new ExpressCode() { code = "eyoupost", name = "易友通" });
            code.Add(new ExpressCode() { code = "sagawa", name = "佐川急便" });
            code.Add(new ExpressCode() { code = "ztky", name = "中通快运" });
            code.Add(new ExpressCode() { code = "zxwl", name = "无锡纵行物流" });
            code.Add(new ExpressCode() { code = "zysf", name = "转运四方" });
            code.Add(new ExpressCode() { code = "correos_chile", name = "智利邮政(Correos Chile)" });
            code.Add(new ExpressCode() { code = "zhonghuan", name = "中环快递" });
            code.Add(new ExpressCode() { code = "zhongtie", name = "中铁快运" });
            code.Add(new ExpressCode() { code = "zhongyou", name = "中邮物流" });
            code.Add(new ExpressCode() { code = "zmkm", name = "芝麻开门" });
            code.Add(new ExpressCode() { code = "zzjh", name = "郑州建华快递" });
            code.Add(new ExpressCode() { code = "ztwy", name = "中天万运快递" });
            code.Add(new ExpressCode() { code = "zengyi", name = "增益快递" });

            return code;
        }

        
    }
}
